- name: Install common requirements
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: yes
  become: yes

- name: Install beats
  ansible.builtin.import_tasks:
    file: ./install-beats.yaml
  become: yes
