- name: Create secret directory
  ansible.builtin.file:
    path: "{{secret_dir}}/squid"
    state: directory

- name: Create private key for self-signed certificate
  community.crypto.openssl_privatekey:
    path: "{{secret_dir}}/squid/squid.key"
    size: 2048
    backup: true
# - name: Create certificate signing request (CSR) for self-signed certificate
#   community.crypto.openssl_csr:
#     path: "{{secret_dir}}/squid/squid.csr"
#     privatekey_path: "{{secret_dir}}/squid/squid.key"

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr:
    path: "{{secret_dir}}/squid/squid.csr"
    privatekey_path: "{{secret_dir}}/squid/squid.key"
    common_name: "{{cert_ip_address}}"
    organization_name: "{{cert_organization_name}}"
    subject_alt_name:
      - "IP:{{cert_ip_address}}"
    backup: true
  register: csr

- name: Create self-signed certificate
  community.crypto.x509_certificate:
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    path: "{{secret_dir}}/squid/squid.pem"
    privatekey_path: "{{secret_dir}}/squid/squid.key"
    # csr_content: "{{ csr.csr }}"
    backup: true
    csr_path: "{{secret_dir}}/squid/squid.csr"

- name: Create Diffie-Hellman parameters
  community.crypto.openssl_dhparam:
    path: "{{secret_dir}}/squid/dhparam.pem"
    size: 2048
